/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controladores.ClienteG;
import Controladores.Conexion;
import Modelos.Cliente;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sandracano
 */
public class ReporteClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteClientes
     */
    
    public Conexion conexion;
    public Connection link;
    public ReporteClientes() {
        initComponents();
        
        conexion=new Conexion();
        link=conexion.Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TClientes = new javax.swing.JTable();
        btnDatos = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        TClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombres", "Apellidos", "Fecha Nacimiento", "Region", "Comuna"
            }
        ));
        TClientes.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(TClientes);

        btnDatos.setText("Cargar");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDatos)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDatos)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        // TODO add your handling code here:
        
        
        ArrayList<Cliente>Lista=new ArrayList<Cliente>();
        ClienteG cliente=new ClienteG();
        Lista=cliente.Leer(link);
        
        
        
        for(int i=0;i<Lista.size();i++){
            System.out.println(Lista.get(i).getNombres());
            Object[] row = { Lista.get(i).getRut(),Lista.get(i).getNombres(),Lista.get(i).getApellidos(),Lista.get(i).getFechaNacimiento(),Lista.get(i).getRegion(),Lista.get(i).getComuna()};
            DefaultTableModel model = (DefaultTableModel) TClientes.getModel();
            model.insertRow(i, row);
        }

        
        
    }//GEN-LAST:event_btnDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TClientes;
    private javax.swing.JButton btnDatos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
